---
# tasks file for shaarli
- name: Install required packages
  community.general.apk:
    name: "{{ packages }}"
    state: latest

- name: Add subdirectory alias into apache configuration
  ansible.builtin.blockinfile:
    path: /etc/apache2/httpd.conf
    block: |
      Alias "/shaarli" "/var/www/Shaarli"
      <Directory "/var/www/Shaarli">
        AllowOverride All
        Require all granted
      </Directory>

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/shaarli/Shaarli/releases/download/v0.13.0/shaarli-v0.13.0-full.zip
    dest: /var/www
    remote_src: yes
    owner: apache
    group: apache

- name: Reload apache service
  ansible.builtin.service:
    name: apache2
    state: reloaded
