---
# tasks file for update
- name: update system packages list
  register: updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: upgrade system and apps
  register: upgraded
  when: updated.cache_updated
  ansible.builtin.apt:
    upgrade: dist

#- name: check for need to reboot
#  ansible.builtin.stat:
#    path: /var/run/reboot-required
#  register: stat_result
#
#- name: reboot server
#  ansible.builtin.reboot:
#  when: stat_result.stat.exists

#- name: reboot server
#  register: rebooted
#  when: upgraded is changed and ansible_connection != 'local'
#  ansible.builtin.reboot:
#    reboot_timeout: 90

- name: remove unused packages
  when: upgraded is changed
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: clean
  when: upgraded is changed
  ansible.builtin.apt:
    autoclean: true
