---
# tasks file for take_over
- name: Remove ansible home directory
  ansible.builtin.file:
    path: /home/ansible
    state: absent

- name: Remove ansible user to sudoers file
  community.general.sudoers:
    name: ansible
    user: ansible
    nopassword: true
    commands: ALL
    runas: "ALL:ALL"
    state: absent

- name: Delete ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    system: true
    home: /home/ansible
    password: '*'
    state: absent
