---
# tasks file for nfs - client
- name: "Creating {{ mount.path }} directory"
  ansible.builtin.file:
    path: "{{ mount.path }}"
    state: directory
    mode: '755'

- name: "Setting automount file for {{ mount.path }}"
  ansible.builtin.template:
    src: automount.j2
    dest: "/etc/systemd/system/{{ mount.filename }}.automount"
    mode: '644'

- name: "Setting mount file for {{ mount.path }}"
  ansible.builtin.template:
    src: mount.j2
    dest: "/etc/systemd/system/{{ mount.filename }}.mount"
    mode: '644'

- name: "Enable systemd {{ mount.filename }}.automount"
  ansible.builtin.systemd_service:
    name: "{{ mount.filename }}.automount"
    state: started
    enabled: true
