---
# tasks file for nfs - server - debian
- name: Installing services packages
  ansible.builtin.apt:
    pkg:
      - nfs-kernel-server
    state: latest

# chercher le service a démarrer et activer
#- name: Start NFS server service
#  ansible.builtin.service:
#    name: apache2
#    state: started
#    enabled: yes
